server:
  port: 8099
app:
  httpUri: http://httpbin.org:80
  name: web-app
  pathWebTaxco: http://localhost:8090/
spring:
  cloud:
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      routes:
      - id: web
        uri: http://baeldung.com
        predicates: 
        - Path=/foo/{segment}
      - id: web-taxco-app
        uri: http://webTaxcoApp:8090/
        predicates: 
        - Path=/article/v0/*
      - id: web-taxco-app2
        uri: http://webTaxcoApp:8090/
        predicates: 
        - Path=/bracelet/v0/**
      - id: web-taxco-app3
        uri: http://webTaxcoApp:8090/
        predicates: 
        - Path=/chain/v0/**
      - id: web-taxco-app4
        uri: http://webTaxcoApp:8090/
        predicates: 
        - Path=/order/v0/**
      - id: otros
        predicates: 
        - Path=/delay/{segment}
        uri: http://httpbin.org:80
      - id: web-authentication
        uri: http://webAuthentication:8091
        filters:
         - AddRequestParameter=tsec, XXXWWWYYY
         - AddResponseHeader=postFilter, spring_gateway
         - AddResponseHeader=spring-gateway, gateway
        predicates:
        - Path=/authetication/v0/**
      - id: managment
        uri: http://webTaxcoApp:8090
        filters:
         - AddResponseHeader=spring-gateway, gateway
        predicates:
        - Path=/management/*
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
logging:
  level:
    ROOT: INFO
    org.springframework.cloud.context.config: debug